
on: push
      
name: Render manuscript

jobs:
  render:
    name: Render RMarkdown
    runs-on: ubuntu-18.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - uses: r-lib/actions/setup-tinytex@master
      - name: Install system dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update -y && sudo apt-get install -y libcurl4-openssl-dev
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes', repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
          Rscript -e "remotes::install_deps(dependencies = TRUE, repos = 'https://demo.rstudiopm.com/all/__linux__/bionic/latest')"
      - name: Render mansucript
        run: |-